# Generated by Django 4.1.6 on 2023-07-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_furnature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Furnature',
        ),
    ]
