# Generated by Django 4.1.6 on 2023-07-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_electro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Electro',
        ),
        migrations.DeleteModel(
            name='Mebel',
        ),
    ]
