# Generated by Django 4.1.6 on 2023-07-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_product2_delete_mebel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='products3/%Y/%m/%d')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product2',
            name='image',
            field=models.ImageField(upload_to='products2/%Y/%m/%d/'),
        ),
    ]
