# Generated by Django 4.1.6 on 2023-07-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_product3_alter_product2_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product2',
        ),
        migrations.DeleteModel(
            name='Product3',
        ),
    ]
