# Generated by Django 4.1.6 on 2023-07-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_product4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product4',
        ),
    ]
