# Generated by Django 4.1.6 on 2023-07-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_delete_product4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='products4/%Y/%m/%d')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
