# Generated by Django 4.1.6 on 2023-07-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_product4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='product1',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='product2',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='product3',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='product4',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
